const {test}=require('node:test');const a=require('node:assert/strict');const V=require('../assets/engine.js');
const copy=x=>JSON.parse(JSON.stringify(x));
function doAct(s,type,id,value){const r=V.act(s,type,id,value);a.ok(r.ok,r.reason);return r;}
test('O1 restores visibility without curing radio faults; CM preview matches apply',()=>{const s=V.create();const before=V.network(s).service;doAct(s,'connect',0);a.equal(V.network(s).service,before);a.equal(s.sites[0].locked,true);doAct(s,'stage',0,'normal');const predicted=V.previewChange(s,0);doAct(s,'apply',0);a.equal(V.network(s).service,predicted.service);a.equal(s.sites[0].locked,false);doAct(s,'rollback',0);a.equal(s.sites[0].locked,true);});
test('invalid actions do not spend resources and no action can overspend',()=>{const s=V.create();const before=copy(s);a.equal(V.act(s,'apply',0).ok,false);a.deepEqual(s,before);s.ap=0;a.equal(V.act(s,'repair',2).ok,false);s.ap=4;s.credits=0;a.equal(V.act(s,'repair',2).ok,false);s.credits=99;s.parts=0;a.equal(V.act(s,'repair',2).ok,false);});
test('PM and rApp prerequisites, one collection per day, freshness and slot limit',()=>{const s=V.create(2);a.equal(V.act(s,'pm').ok,false);doAct(s,'connect',2);doAct(s,'pm');a.equal(V.act(s,'pm').ok,false);a.equal(V.act(s,'install','balance').ok,false);doAct(s,'install','energy');V.settle(s);a.ok(V.fresh(s));doAct(s,'pm');doAct(s,'install','balance');a.equal(V.act(s,'install','heal').ok,false);s.day+=2;a.equal(V.fresh(s),false);a.equal(V.network(s).appsReady,false);});
test('eco policy has a measurable energy/capacity tradeoff, balancing conserves demand',()=>{const s=V.create(5);s.policy='capacity';const cap=V.network(s);s.policy='eco';const eco=V.network(s);a.ok(eco.energyCost<cap.energyCost);a.ok(eco.service<=cap.service);a.ok(eco.conflict);for(let i=0;i<3;i++)a.ok(eco.served[i]<=V.forecast(s).demand[i]);a.ok(eco.transfers.reduce((a,t)=>a+t.units,0)<=12);});
test('tomorrow forecast predicts actual storm target and protection avoids O1 loss',()=>{const s=V.create(4,'test');s.day=3;const f=V.forecast(s,4);a.ok(f.storm);const t=copy(s);s.sites[f.target].health=100;t.sites[f.target].health=100;s.sites[f.target].o1=true;t.sites[f.target].o1=true;t.sites[f.target].hardened=true;V.settle(s);V.settle(t);a.equal(s.sites[f.target].health,65);a.equal(s.sites[f.target].o1,false);a.equal(t.sites[f.target].health,92);a.equal(t.sites[f.target].o1,true);});
test('Watchkeeper repairs configuration before day-end calculation but not hardware',()=>{const s=V.create();s.apps=['heal'];s.pmDay=1;s.samples=2;s.sites[0].o1=true;const damaged=s.sites[2].health;const r=V.settle(s);a.equal(s.sites[0].locked,false);a.equal(s.sites[2].health,damaged);a.ok(r.notes.some(n=>n.startsWith('Watchkeeper')));});
test('reviews are side-effect free when simulated on copies; same seed repeats',()=>{const s=V.create(7,'repeat'),before=copy(s);const one=V.settle(copy(s)),two=V.settle(copy(s));a.deepEqual(one,two);a.deepEqual(s,before);a.deepEqual(V.forecast(s,8),V.forecast(V.create(7,'repeat'),8));});
test('neglect fails and score is capped; ended games cannot mutate',()=>{const s=V.create();s.sites.forEach(x=>x.locked=true);while(!s.ended)V.settle(s);a.equal(s.won,false);a.ok(s.score<=599);const before=copy(s);a.equal(V.settle(s),null);a.equal(V.act(s,'parts').ok,false);a.deepEqual(s,before);});
function play(chapter,seed){const s=V.create(chapter,seed);let guard=0;while(!s.ended&&guard++<20){
 for(let i=0;i<3;i++){if(!s.sites[i].o1&&V.quote(s,'connect',i).ok)V.act(s,'connect',i);if(s.sites[i].locked||s.sites[i].drift){V.act(s,'inspect',i);V.act(s,'stage',i,'normal');V.act(s,'apply',i);}if(s.sites[i].health<85&&V.quote(s,'repair',i).ok)V.act(s,'repair',i);}
 if(s.policy!=='balanced')V.act(s,'policy',undefined,'balanced');
 const next=V.forecast(s,s.day+1);if(next.storm&&V.quote(s,'harden',next.target).ok)V.act(s,'harden',next.target);
 for(const i of [1,0,2])if(s.sites[i].level<2&&V.quote(s,'upgrade',i).ok)V.act(s,'upgrade',i);
 if(s.parts<2&&V.quote(s,'parts').ok)V.act(s,'parts');
 V.settle(s);
 }return s;}
test('all seven chapters are winnable with a forecast-aware repair/build strategy',()=>{for(let ch=1;ch<=7;ch++){const s=play(ch,'valley-'+ch);a.ok(s.won,`Chapter ${ch}: average ${s.history.reduce((a,r)=>a+r.service,0)/s.history.length}; trust ${s.trust}`);a.ok(s.score<=1000);a.equal(s.history.length,s.days);}});
test('server replay ignores claimed totals and rejects impossible moves',()=>{const {verify}=require('../scripts/verify-score.cjs');const s=V.create(1,'valley-1'),moves=[];while(!s.ended){moves.push(['end']);V.settle(s);}const result=verify({version:3,chapter:1,seed:'valley-1',mode:'ranked',moves,score:999999},'Tester',1,'2026-10-03');a.equal(result.score,s.score);a.throws(()=>verify({version:3,chapter:1,seed:'valley-1',mode:'ranked',moves:[['apply',0]]},'Tester',1,''));});
